# Generated by Django 4.1.2 on 2022-10-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('parentesco', models.CharField(max_length=50)),
            ],
        ),
    ]
